package server

func init() {
	platformNames = map[string]string{
		"acfun":        "AcFun",
		"bilibili":     "哔哩哔哩",
		"cctv":         "央视网",
		"doupai":       "逗拍",
		"douyin":       "抖音",
		"haokan":       "好看视频",
		"huoshan":      "火山",
		"huya":         "虎牙",
		"kuaishou":     "快手",
		"lishipin":     "梨视频",
		"lvzhou":       "绿洲",
		"meipai":       "美拍",
		"pipigaoxiao":  "皮皮搞笑",
		"pipixia":      "皮皮虾",
		"qqvideo":      "腾讯视频",
		"quanmin":      "度小视",
		"quanminkge":   "全民K歌",
		"redbook":      "小红书",
		"sixroom":      "六间房",
		"sohu":         "搜狐视频",
		"twitter":      "X/Twitter",
		"weibo":        "微博",
		"weishi":       "微视",
		"xigua":        "西瓜视频",
		"xinpianchang": "新片场",
		"zuiyou":       "最右",
	}

	externalAdminTestSampleNames = map[string]string{
		"abc":         "ABC",
		"arte":        "ArteTV",
		"baidutieba":  "百度贴吧",
		"beacon":      "Beacon",
		"c56":         "56视频",
		"ccc":         "CCC",
		"cctalk":      "CCtalk",
		"cctvnews":    "央视新闻",
		"chinadaily":  "中国日报",
		"dongchedi":   "懂车帝",
		"eastday":     "东方网",
		"eyepetizer":  "开眼视频",
		"foxnews":     "Fox News",
		"genius":      "Genius",
		"huanqiu":     "环球网",
		"youtube":     "YouTube",
		"tiktok":      "TikTok",
		"instagram":   "Instagram",
		"facebook":    "Facebook",
		"iqiyi":       "爱奇艺",
		"kakao":       "Kakao TV",
		"kankannews":  "看看新闻",
		"ku6":         "酷6",
		"kugoumv":     "酷狗MV",
		"leshi":       "乐视",
		"m1905":       "1905电影网",
		"mgtv":        "芒果TV",
		"mingpao":     "明报",
		"open163":     "网易公开课",
		"people":      "人民网",
		"playerpl":    "Player.pl",
		"plusfifa":    "FIFA+",
		"reddit":      "Reddit",
		"rutube":      "Rutube",
		"sina":        "新浪视频",
		"tbnuk":       "TBN UK",
		"ted":         "TED",
		"unity":       "Unity Learn",
		"vimeo":       "Vimeo",
		"dailymotion": "Dailymotion",
		"m3u8":        "M3U8",
		"wesing":      "WeSing",
		"wittytv":     "WittyTV",
		"wwe":         "WWE",
		"www163":      "网易视频",
		"xinhuanet":   "新华网",
		"xuexicn":     "学习强国",
		"yinyuetai":   "音悦台",
		"youku":       "优酷",
		"zhihu":       "知乎",

		"music_apple":       "Apple Music",
		"music_bodian":      "波点音乐",
		"music_deezer":      "Deezer",
		"music_fivesing":    "5SING音乐",
		"music_fma":         "Free Music Archive",
		"music_jamendo":     "Jamendo",
		"music_jiosaavn":    "JioSaavn",
		"music_joox":        "JOOX",
		"music_kugou":       "酷狗音乐",
		"music_kuwo":        "酷我音乐",
		"music_migu":        "咪咕音乐",
		"music_netease":     "网易云音乐",
		"music_qianqian":    "千千音乐",
		"music_qobuz":       "Qobuz",
		"music_qq":          "QQ音乐",
		"music_soda":        "汽水音乐",
		"music_soundcloud":  "SoundCloud",
		"music_spotify":     "Spotify",
		"music_streetvoice": "StreetVoice",
		"music_tidal":       "TIDAL",
	}

	defaultAdminTestLinks = []adminTestLink{
		{Name: "抖音", URL: "https://v.douyin.com/i2YArd1J/"},
		{Name: "快手", URL: "https://v.kuaishou.com/3yItmR"},
		{Name: "哔哩哔哩", URL: "https://www.bilibili.com/video/BV1634y1w7Nu/"},
		{Name: "微博", URL: "https://h5.video.weibo.com/show/1034:4915132212641842"},
		{Name: "小红书", URL: "http://xhslink.com/a/ELECa0m0DXccb"},
		{Name: "皮皮虾", URL: "https://h5.pipix.com/item/7111320087503575303"},
		{Name: "皮皮搞笑", URL: "https://h5.pipigx.com/pp/post/808595934847"},
		{Name: "全民K歌", URL: "https://kg.qq.com/node/play?s=d-GYCadMOClC7d_0&shareuid=64959a822728338a32&topsource=a0_pn201001006_z1_u687725416_l1_t1579315797__"},
		{Name: "度小视", URL: "https://xspshare.baidu.com/sv?source=share-h5&pd=qm_share_mvideo&vid=3712722043658570249"},
		{Name: "西瓜视频", URL: "https://www.ixigua.com/7359024563227656714"},
		{Name: "微视", URL: "https://video.weishi.qq.com/vfD4rz6U"},
		{Name: "好看视频", URL: "https://haokan.baidu.com/v?vid=4737540153193310732&pd=pcshare"},
		{Name: "梨视频", URL: "https://www.pearvideo.com/detail_1768812?st=7"},
		{Name: "央视网", URL: "https://tv.cctv.com/2026/05/09/VIDEy4R1ur8n3rdXIUlV8bDu260509.shtml"},
		{Name: "搜狐视频", URL: "http://my.tv.sohu.com/us/335942214/399571612.shtml"},
		{Name: "虎牙", URL: "https://v.huya.com/play/754425177.html"},
		{Name: "AcFun", URL: "https://www.acfun.cn/v/ac32776052"},
		{Name: "六间房", URL: "https://v.6.cn/minivideo/2716610"},
		{Name: "绿洲", URL: "https://m.oasis.weibo.cn/v1/h5/share?sid=4568005764186704"},
		{Name: "美拍", URL: "https://www.meipai.com/video/990/6870563584084037566"},
		{Name: "腾讯视频", URL: "https://v.qq.com/x/page/l3502vppd13.html"},
		{Name: "最右", URL: "https://share.xiaochuankeji.cn/hybrid/share/post?pid=407260908&vid=2492069614&zy_to=applink&share_count=1&m=72986390f8e3651c01fe06c56bccfb56&d=1eed7b49c0a6141fa1913307c450274fa5878ca53265df2c35e2f4fce0bffbfa&app=zuiyou&recommend=r0&name=n0&title_type=t0"},
		{Name: "YouTube", URL: "https://www.youtube.com/watch?v=oGsXa6slchc&t=2s"},
		{Name: "TikTok", URL: "https://www.tiktok.com/@nathanharenice/video/7413042588074200326"},
		{Name: "Instagram", URL: "https://www.instagram.com/reel/C62MdoDOWCr/"},
		{Name: "Twitter/X", URL: "https://x.com/Eminem/status/943590594491772928"},
		{Name: "Facebook", URL: "https://facebook.com/CTSHSTT/videos/374811976811983/"},
		{Name: "Vimeo", URL: "https://vimeo.com/76979871"},
		{Name: "Dailymotion", URL: "https://www.dailymotion.com/video/x7t3la2"},
		{Name: "M3U8", URL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"},
		{Platform: "abc", Name: "ABC", URL: "https://www.abc.net.au/btn/classroom/wwi-centenary/10527914"},
		{Platform: "arte", Name: "ArteTV", URL: "https://www.arte.tv/en/videos/127781-000-A/arte-reportage/"},
		{Platform: "baidutieba", Name: "百度贴吧", URL: "https://tieba.baidu.com/p/7280373361"},
		{Platform: "cctalk", Name: "CCtalk", URL: "https://www.cctalk.com/v/17604950351552?sid=1760494906733025"},
		{Platform: "dongchedi", Name: "懂车帝", URL: "https://www.dongchedi.com/video/7595864547580658200"},
		{Platform: "iqiyi", Name: "爱奇艺", URL: "https://www.iqiyi.com/v_1wc7muawbrc.html"},
		{Platform: "mgtv", Name: "芒果TV", URL: "https://www.mgtv.com/l/100026064/19868457.html?fpa=1684&fpos=&lastp=ch_home&cpid=5"},
		{Platform: "open163", Name: "网易公开课", URL: "https://open.163.com/newview/movie/free?pid=WIAL798Q9&mid=BIAL799D2"},
		{Platform: "reddit", Name: "Reddit", URL: "https://www.reddit.com/r/videos/comments/6rrwyj/that_small_heart_attack/"},
		{Platform: "ted", Name: "TED", URL: "https://www.ted.com/talks/alanna_shaikh_why_covid_19_is_hitting_us_now_and_how_to_prepare_for_the_next_outbreak"},
		{Platform: "youku", Name: "优酷", URL: "https://v.youku.com/v_show/id_XNDU1MTg1NjM2OA=="},
		{Platform: "zhihu", Name: "知乎", URL: "https://www.zhihu.com/zvideo/1342930761977176064"},

		{Platform: "beacon", Name: "Beacon", URL: "https://beacon.tv/content/welcome-to-beacon", Note: "videodl 每日状态页样本"},
		{Platform: "c56", Name: "56视频", URL: "https://www.56.com/u11/v_MTk5NjI0OTIw.html", Note: "videodl 每日状态页样本"},
		{Platform: "ccc", Name: "CCC", URL: "https://media.ccc.de/v/30C3_-_5443_-_en_-_saal_g_-_201312281830_-_introduction_to_processor_design_-_byterazor#video", Note: "videodl 每日状态页样本"},
		{Platform: "cctvnews", Name: "央视新闻", URL: "https://content-static.cctvnews.cctv.com/snow-book/video.html?item_id=15184105708774284671", Note: "videodl 每日状态页样本"},
		{Platform: "chinadaily", Name: "中国日报", URL: "https://www.chinadaily.com.cn/a/202604/07/WS69d4c582a310d6866eb42089.html", Note: "videodl 每日状态页样本"},
		{Platform: "eastday", Name: "东方网", URL: "https://nw.eastday.com/bjzx/20260403/cc9f70957fd8439da55c921920a6f73a.html", Note: "videodl 每日状态页样本"},
		{Platform: "eyepetizer", Name: "开眼视频", URL: "https://home.eyepetizer.net/video/video-detail?resource_id=219143&resource_type=pgc_video", Note: "videodl 每日状态页样本"},
		{Platform: "foxnews", Name: "Fox News", URL: "https://www.foxnews.com/video/6385658327112", Note: "videodl 每日状态页样本"},
		{Platform: "genius", Name: "Genius", URL: "https://genius.com/videos/Halle-breaks-down-the-meaning-of-bite-your-lip", Note: "videodl 每日状态页样本"},
		{Platform: "huanqiu", Name: "环球网", URL: "https://v.huanqiu.com/article/4RGKR80sTBx", Note: "videodl 每日状态页样本"},
		{Platform: "kakao", Name: "Kakao TV", URL: "http://tv.kakao.com/channel/2671005/cliplink/301965083", Note: "videodl 每日状态页样本"},
		{Platform: "kankannews", Name: "看看新闻", URL: "https://www.kankanews.com/detail/PbwRzE9qow4", Note: "videodl 每日状态页样本"},
		{Platform: "ku6", Name: "酷6", URL: "https://www.ku6.com/video/detail?id=McZoSe_hgG_jwzy7pQLqvMJ3IoI.", Note: "videodl 每日状态页样本"},
		{Platform: "kugoumv", Name: "酷狗MV", URL: "https://www.kugou.com/mv/8cwxy96/", Note: "videodl 每日状态页样本"},
		{Platform: "leshi", Name: "乐视", URL: "https://www.le.com/ptv/vplay/78006876.html#vid=78006876", Note: "videodl 每日状态页样本"},
		{Platform: "m1905", Name: "1905电影网", URL: "https://www.1905.com/video/play/1751538.shtml", Note: "videodl 每日状态页样本"},
		{Platform: "mingpao", Name: "明报", URL: "https://news.mingpao.com/pns/%e5%89%af%e5%88%8a/article/20260428/s00005/1777310866112/%e6%96%b0%e8%88%88%e6%9d%bf%e7%b6%b2%e7%90%83%e6%98%93%e5%ad%b8%e9%9b%a3%e7%b2%be-%e3%80%8c%e7%a5%9e%e9%9a%8a%e5%8f%8b%e3%80%8d%e7%89%86%e7%b6%b2%e6%94%b9%e8%ae%8a%e7%90%83%e9%81%93%e8%87%b4%e5%8b%9d#goog_rewarded", Note: "videodl 每日状态页样本"},
		{Platform: "people", Name: "人民网", URL: "http://v.people.cn/n1/2026/0421/c431305-40705569.html", Note: "videodl 每日状态页样本"},
		{Platform: "playerpl", Name: "Player.pl", URL: "https://player.pl/filmy-online/1800-gramow,169874", Note: "videodl 每日状态页样本"},
		{Platform: "plusfifa", Name: "FIFA+", URL: "https://www.plus.fifa.com/en/player/580e692e-e8fc-4ad1-a649-5ec0af83f94d?catalogId=5f24e303-ff42-499f-9d7a-b4f8e0eff2ce", Note: "videodl 每日状态页样本"},
		{Platform: "rutube", Name: "Rutube", URL: "https://rutube.ru/video/381e239f73b2d475bc0c2e459f531abb/", Note: "videodl 每日状态页样本"},
		{Platform: "sina", Name: "新浪视频", URL: "http://video.sina.com.cn/view/250587748.html", Note: "videodl 每日状态页样本"},
		{Platform: "tbnuk", Name: "TBN UK", URL: "https://watch.tbn.uk/watch/vod/52157303/identity-and-belonging", Note: "videodl 每日状态页样本"},
		{Platform: "unity", Name: "Unity Learn", URL: "https://learn.unity.com/course/2d-beginner-game-sprite-flight/tutorial/set-up-your-2d-game-world?version=6.0", Note: "videodl 每日状态页样本"},
		{Platform: "wesing", Name: "WeSing", URL: "https://kg.qq.com/node/user/bb132c338e/song/play-edLkcwAsRj?s=bCyoDlbCUhcjXbkQ&shareuid=&topsource=znxvljkwehoit_rqojkwehfguioqef_fnajkgfb&g_f=", Note: "videodl 每日状态页样本"},
		{Platform: "wittytv", Name: "WittyTV", URL: "https://www.wittytv.it/amici/giovedi-22-gennaio-il-quotidiano-di-amici/", Note: "videodl 每日状态页样本"},
		{Platform: "wwe", Name: "WWE", URL: "https://www.wwe.com/videos/daniel-bryan-vs-andrade-cien-almas-smackdown-live-sept-4-2018", Note: "videodl 每日状态页样本"},
		{Platform: "www163", Name: "网易视频", URL: "https://www.163.com/v/video/VDHQNAVSD.html?clickfrom=video_like", Note: "videodl 每日状态页样本"},
		{Platform: "xinhuanet", Name: "新华网", URL: "https://www.news.cn/fortune/20260409/01e2ba78799248769b889746e9a5bbe5/c.html", Note: "videodl 每日状态页样本"},
		{Platform: "xuexicn", Name: "学习强国", URL: "https://www.xuexi.cn/lgpage/detail/index.html?id=6898516301450608472", Note: "videodl 每日状态页样本"},
		{Platform: "yinyuetai", Name: "音悦台", URL: "https://www.yinyuetai.com/watch/7200480383631265792?listType=swiper&listId=6998475633361805312", Note: "videodl 每日状态页样本"},

		{Platform: "music_apple", Name: "Apple Music", URL: "https://music.apple.com/cn/playlist/%E5%8D%81%E5%A4%A7%E4%B8%93%E8%BE%91/pl.u-mJy81mECzBL49zM", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_bodian", Name: "波点音乐", URL: "https://h5app.kuwo.cn/m/bodian/collection.html?uid=1798690&playlistId=1669719&source=5&ownerId=1798690", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_deezer", Name: "Deezer", URL: "https://www.deezer.com/us/playlist/4697225044", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_fivesing", Name: "5SING音乐", URL: "https://5sing.kugou.com/yeluoluo/dj/631b3fa72418b11003089b8d.html", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_fma", Name: "Free Music Archive", URL: "https://freemusicarchive.org/member/Creative_Commons/cc-20th-anniversary-open-mix", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_jamendo", Name: "Jamendo", URL: "https://www.jamendo.com/playlist/500544876/best-of-february-2020", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_jiosaavn", Name: "JioSaavn", URL: "https://www.jiosaavn.com/featured/world-music-day-telugu/3sLj61YBHdI_", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_joox", Name: "JOOX", URL: "https://www.joox.com/hk/playlist/MqgK_LYD3Sb3I9Iziq+8NA==", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_kugou", Name: "酷狗音乐", URL: "https://www.kugou.com/yy/special/single/3280341.html", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_kuwo", Name: "酷我音乐", URL: "https://www.kuwo.cn/playlist_detail/2358858706", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_migu", Name: "咪咕音乐", URL: "https://music.migu.cn/v5/#/playlist?playlistId=228114498&playlistType=ordinary", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_netease", Name: "网易云音乐", URL: "https://music.163.com/#/playlist?id=3039971654", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_qianqian", Name: "千千音乐", URL: "https://music.91q.com/songlist/295893", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_qobuz", Name: "Qobuz", URL: "https://open.qobuz.com/playlist/22318381", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_qq", Name: "QQ音乐", URL: "https://y.qq.com/n/ryqq_v2/playlist/8740590963", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_soda", Name: "汽水音乐", URL: "https://qishui.douyin.com/s/iHFSgNKw/", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_soundcloud", Name: "SoundCloud", URL: "https://soundcloud.com/pandadub/sets/the-lost-ship", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_spotify", Name: "Spotify", URL: "https://open.spotify.com/playlist/37i9dQZF1E8NWHOpySOxQd", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_streetvoice", Name: "StreetVoice", URL: "https://www.streetvoice.cn/morgan22/playlists/436444/", Note: "musicdl 播放列表样本，需通用解析器"},
		{Platform: "music_tidal", Name: "TIDAL", URL: "https://tidal.com/playlist/a94e7dce-da66-413d-81a5-990328afa3c9", Note: "musicdl 播放列表样本，需通用解析器"},
	}
}
