CREATE TABLE IF NOT EXISTS platform_test_samples (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  platform_key VARCHAR(64) NOT NULL,
  display_name VARCHAR(64) NOT NULL DEFAULT '',
  sample_url TEXT NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  note VARCHAR(255) NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_platform_key (platform_key),
  KEY idx_enabled_sort (enabled, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
