CREATE TABLE IF NOT EXISTS platform_test_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id CHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'completed',
  message VARCHAR(512) NOT NULL DEFAULT '',
  duration_ms INT UNSIGNED NOT NULL DEFAULT 0,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_run_id (run_id),
  KEY idx_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS platform_test_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id CHAR(32) NOT NULL,
  platform_key VARCHAR(64) NOT NULL,
  display_name VARCHAR(128) NOT NULL DEFAULT '',
  sample_url TEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'completed',
  success TINYINT NOT NULL DEFAULT 0,
  result_platform VARCHAR(64) NOT NULL DEFAULT '',
  result_type VARCHAR(32) NOT NULL DEFAULT '',
  parser_engine VARCHAR(64) NOT NULL DEFAULT '',
  result_title VARCHAR(512) NOT NULL DEFAULT '',
  share_id VARCHAR(128) NOT NULL DEFAULT '',
  duration_ms INT UNSIGNED NOT NULL DEFAULT 0,
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_run_sort (run_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
